"""
Django settings for TravelFun project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

# C:\practice_iSpan\OJTP01_TravelFunProject\TravelFun
# C:\\practice_iSpan\\OJTP01_TravelFunProject\\TravelFun\\databaseSetting.env'

from pathlib import Path

from decouple import Config, RepositoryEnv

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 確認環境變數檔案的路徑
env_path = os.path.join(BASE_DIR, 'databaseSetting.env.txt')

database_env_file = RepositoryEnv(env_path)
database_config = Config(database_env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--0doe4q3-z98oq#h^fjn@x6-!+xe6$#vi248!5q^9uj9--=g48'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main_app',
    'food_app',
    'shop_app',
    'index.apps.IndexConfig',
    'commodity.apps.CommodityConfig',
    'shopper.apps.ShopperConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # 安全機制
    'django.contrib.sessions.middleware.SessionMiddleware', # Session function
    'django.middleware.locale.LocaleMiddleware', #添加LocalMiddleware 支援中文顯示 p.41
    'django.middleware.common.CommonMiddleware', #處理請求信息，規範請求內容
    'django.middleware.csrf.CsrfViewMiddleware', #開啟CSRF防護
    'django.contrib.auth.middleware.AuthenticationMiddleware', #開啟內置用戶認證系統
    'django.contrib.messages.middleware.MessageMiddleware', #開啟內置訊息提示功能
    'django.middleware.clickjacking.XFrameOptionsMiddleware', #防止惡意程式點擊綁架
]
#指定所有路由地址的總入口
ROOT_URLCONF = 'TravelFun.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TravelFun.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default':
    {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': database_config('DB_NAME'),
        'USER': database_config('DB_USER'),
        'PASSWORD': database_config('DB_PASSWORD'),
        'HOST': database_config('DB_HOST'),
        'PORT': database_config('DB_PORT', default='3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
#添加並設置屬性 STATICFILES_DIRS
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
#收集靜態資源存放在資料夾，並與server建立映射關係，若處於開發階段則不必使用STATIC_ROOT
# STATIC_ROOT = BASE_DIR / 'AllStatic',

#設置MEDIA媒體資源資料夾讀取路徑
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
